### PR TITLE
ENH: Attachments

### PR DESCRIPTION
**Pull request by IoannisNezis**
This is the corrisponding PR for [this](https://github.com/ContactEngineering/topobank/pull/1081) PR in the main repo.
When this is done there will be a viewer and editor for the attachments of surfaces and topographies.
The new component will:
- [x] list the attached files
- [x] have a working upload form
- [x] have a working delete button

### CODE REVIEW

**Comment by pastewka** [comment]
Looks good - @tdbjacobs, any thoughts and/or requirements regarding attachments?

**Comment by tdbjacobs** [comment]
Looks great!

But we should probably add a little explanatory text that attachments should not be raw data, but simply helper files that may be useful in evaluating the raw data (such as microscope images or other related (non-topography) content.

Also, do we need a "flag inappropriate content" button just in case some one misuses our attachments?

Also we should probably put a size limit so that it doesnt take up unreasonable storage

Tevis


Tevis Jacobs
Mechanical Engineering and Materials Science
University of Pittsburgh
________________________________

**Comment by pastewka** [comment]
Two comments:

* We discussed that there should be attachments for measurements and digital surface twins.

* What is the typical size of an attachment for either of those, i.e. what is a good size limit?

Storage does not cost much but I agree that there should be some limit just to fight abuse.

**Comment by pastewka** [comment]
This looks good @IoannisNezis - no comments

**Review by pastewka — APPROVED** [review]

**Pull request merged**
